name: brain_surgery_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - cudatoolkit=11.2
  - pytorch=1.10.0
  - transformers
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - umap-learn
  - pip
  - pip:
      - torchtext
      - sentencepiece